# Generated by Django 6.0.2 on 2026-02-05 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Prénom de l'utilisateur requis.", max_length=50, verbose_name='prénom')),
                ('last_name', models.CharField(help_text="Nom de famille de l'utilisateur requis.", max_length=50, verbose_name='nom de famille')),
                ('email', models.EmailField(help_text="L'adresse email valide est requise pour l'identification.", max_length=254, verbose_name='adresse email')),
                ('subject', models.CharField(max_length=150, verbose_name='sujet')),
                ('message', models.TextField(verbose_name='message')),
                ('is_processed', models.BooleanField(default=False, verbose_name='traité')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='auteur (membre)')),
            ],
        ),
    ]
